language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
before_script:
  - npm i -g npm@6.1.0
install:
  - npm install
script:
  - npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: 97698d79-7a3e-4117-a320-3497c3326559
  app: refactorci
  on:
    repo: Beto-23/Project-CI